import { Outfit } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const outfit = Outfit({ subsets: ["latin"] ,weight:["400","500","600","700"]});

export const metadata = {
  title: "TCK Blogging",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description}/>
        <link rel="icon" href="/favicon.png" type="x-icon" />


      </Head>

      <body className={outfit.className}>{children}</body>
    </html>
  );
}
